# Nombre del microservicio (común para todos los perfiles)
spring.application.name=microservicios-usuarios

# Aquí eliges qué perfil activar (mysql o postgres)
spring.profiles.active=postgres

# Otras configuraciones comunes (puerto, etc.)
server.port=8001 