

spring.datasource.url=jdbc:mariadb://localhost:3306/db_curso_microservicios_examenes
spring.datasource.username=tuspapas$
spring.datasource.password=tuspapas$

#permite reconstruir facilmente todos los script del orm en la base de datos
spring.jpa.hibernate.ddl-auto=true

#permite imprimir todas las http Request en la consola web
logging.level.org.hibernate.SQL=debug